import type { CardAttackTemplate, CardKind } from './cardTemplateTypes'

export type { CardAttackTemplate, CardKind } from './cardTemplateTypes'
export {
  getCardAttackTemplate,
  getTemplateCooldownTurns,
  isCardTemplateEnabled,
} from './cardTemplateLookup'

export const CARD_ATTACK_TEMPLATES: Readonly<Record<string, CardAttackTemplate>> = {
  strike: {
    label: 'Сильный удар',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 2,
    scaleToken: '40%%',
    cooldownTurns: 3,
    tags: ['skill', 'attack', 'melee'],
    semanticEmojiId: 'sword-red',
    emoji: '🃏',
  },
  shield_bash: {
    label: 'Удар щитом',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 3,
    scaleToken: '45%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'melee'],
    semanticEmojiId: 'shield-gray',
  },
  cleave: {
    label: 'Рассекающий удар',
    kind: 'aoe',
    maxRange: 1,
    aoeSize: 3,
    statSource: 'attack',
    skillFlat: 4,
    scaleToken: '50%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'ranged', 'aoe'],
    semanticEmojiId: 'sword-red',
  },
  battle_cry: {
    label: 'Боевой клич',
    kind: 'buff',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '30%%',
    cooldownTurns: 8,
    tags: ['skill', 'buff'],
    semanticEmojiId: 'horn-gold',
  },
  fireball: {
    label: 'Огненный шар',
    kind: 'aoe',
    maxRange: 3,
    aoeSize: 3,
    statSource: 'magicPower',
    skillFlat: 4,
    scaleToken: '50%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'ranged', 'aoe'],
    semanticEmojiId: 'fire-red',
    emoji: '🔥',
  },
  frost_nova: {
    label: 'Ледяная волна',
    kind: 'aoe',
    maxRange: 3,
    aoeSize: 3,
    statSource: 'magicPower',
    skillFlat: 3,
    scaleToken: '45%%',
    cooldownTurns: 8,
    tags: ['skill', 'attack', 'ranged', 'aoe'],
    semanticEmojiId: 'frost-blue',
  },
  arcane_bolt: {
    label: 'Чародейский луч',
    kind: 'ranged',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 4,
    scaleToken: '55%%',
    cooldownTurns: 4,
    tags: ['skill', 'attack', 'ranged'],
    semanticEmojiId: 'spark-purple',
  },
  power_shot: {
    label: 'Силовой выстрел',
    kind: 'ranged',
    maxRange: 5,
    statSource: 'attack',
    skillFlat: 5,
    scaleToken: '60%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'ranged'],
    semanticEmojiId: 'bow-default',
  },
  multishot: {
    label: 'Залп',
    kind: 'aoe',
    maxRange: 4,
    aoeSize: 3,
    statSource: 'attack',
    skillFlat: 3,
    scaleToken: '45%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'ranged', 'aoe'],
    semanticEmojiId: 'bow-teal',
  },
  snare_trap: {
    label: 'Капкан',
    kind: 'utility',
    maxRange: 4,
    statSource: 'attack',
    skillFlat: 1,
    scaleToken: '20%%',
    cooldownTurns: 8,
    tags: ['skill', 'debuff'],
    semanticEmojiId: 'trap-gray',
  },
  heal: {
    label: 'Исцеление',
    kind: 'heal',
    maxRange: 2,
    statSource: 'healPower',
    skillFlat: 3,
    scaleToken: '25%%',
    cooldownTurns: 8,
    tags: ['skill', 'heal'],
    semanticEmojiId: 'heart-heal',
    emoji: '💚',
  },
  regeneration: {
    label: 'Регенерация',
    kind: 'regen',
    maxRange: 2,
    statSource: 'healPower',
    skillFlat: 2,
    scaleToken: '20%%',
    cooldownTurns: 8,
    tags: ['skill', 'heal'],
    semanticEmojiId: 'heart-blue',
  },
  resurrection: {
    label: 'Воскрешение',
    kind: 'resurrect',
    maxRange: 2,
    statSource: 'healPower',
    skillFlat: 0,
    scaleToken: '30%%',
    cooldownTurns: 16,
    tags: ['skill', 'heal'],
    semanticEmojiId: 'spark-gold',
  },
  backstab: {
    label: 'Удар в спину',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 4,
    scaleToken: '55%%',
    cooldownTurns: 4,
    tags: ['skill', 'attack', 'melee'],
    semanticEmojiId: 'dagger-purple',
  },
  poison_blade: {
    label: 'Отравленный клинок',
    kind: 'dot',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 2,
    scaleToken: '40%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'melee', 'dot'],
    semanticEmojiId: 'drop-green',
  },
  smoke_bomb: {
    label: 'Дымовая шашка',
    kind: 'utility',
    maxRange: 3,
    aoeSize: 3,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '25%%',
    cooldownTurns: 8,
    tags: ['skill', 'debuff', 'aoe'],
    semanticEmojiId: 'smoke-gray',
  },
  holy_strike: {
    label: 'Святой удар',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 4,
    scaleToken: '50%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'melee'],
    semanticEmojiId: 'spark-gold',
  },
  lay_on_hands: {
    label: 'Возложение рук',
    kind: 'heal',
    maxRange: 2,
    statSource: 'healPower',
    skillFlat: 5,
    scaleToken: '40%%',
    cooldownTurns: 10,
    tags: ['skill', 'heal'],
    semanticEmojiId: 'heart-gold',
  },
  divine_shield: {
    label: 'Божественный щит',
    kind: 'buff',
    maxRange: 1,
    statSource: 'healPower',
    skillFlat: 1,
    scaleToken: '25%%',
    cooldownTurns: 10,
    tags: ['skill', 'buff'],
    semanticEmojiId: 'shield-gold',
  },
  shadow_bolt: {
    label: 'Теневой болт',
    kind: 'ranged',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 4,
    scaleToken: '55%%',
    cooldownTurns: 4,
    tags: ['skill', 'attack', 'ranged'],
    semanticEmojiId: 'orb-purple',
  },
  corruption: {
    label: 'Порча',
    kind: 'dot',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 2,
    scaleToken: '40%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'ranged', 'dot'],
    semanticEmojiId: 'skull-green',
  },
  life_drain: {
    label: 'Высасывание жизни',
    kind: 'lifesteal_spell',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 4,
    scaleToken: '50%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'ranged', 'lifesteal'],
    semanticEmojiId: 'vampire-purple',
  },
  frenzy: {
    label: 'Бешенство',
    kind: 'buff',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '35%%',
    cooldownTurns: 8,
    tags: ['skill', 'buff'],
    semanticEmojiId: 'axe-red',
  },
  blood_rage: {
    label: 'Кровавая ярость',
    kind: 'buff',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '40%%',
    cooldownTurns: 8,
    tags: ['skill', 'buff'],
    semanticEmojiId: 'blood-red',
  },
  whirlwind: {
    label: 'Вихрь',
    kind: 'aoe',
    maxRange: 1,
    aoeSize: 3,
    statSource: 'attack',
    skillFlat: 4,
    scaleToken: '50%%',
    cooldownTurns: 8,
    tags: ['skill', 'attack', 'ranged', 'aoe'],
    semanticEmojiId: 'axe-red',
  },
}

export function isHealKind(kind: CardKind): boolean {
  return kind === 'heal' || kind === 'regen' || kind === 'resurrect'
}

export function usesCardAttackDispatch(kind: CardKind): boolean {
  return kind === 'melee' || kind === 'ranged' || kind === 'dot' || kind === 'lifesteal_spell'
}

export function usesCardAoEDispatch(tmpl: CardAttackTemplate): boolean {
  return tmpl.kind === 'aoe' || (tmpl.kind === 'utility' && tmpl.aoeSize !== undefined)
}

export function usesCardHealDispatch(kind: CardKind): boolean {
  return isHealKind(kind)
}

export function usesCardBuffDispatch(kind: CardKind): boolean {
  return kind === 'buff'
}

export function usesCardUtilitySingleDispatch(tmpl: CardAttackTemplate): boolean {
  return tmpl.kind === 'utility' && tmpl.aoeSize === undefined
}
