import type { PassiveTemplate } from './passiveTemplates'

export const ENEMY_PASSIVE_TEMPLATES: Readonly<Record<string, PassiveTemplate>> = {
  enemy_anti_heal_aura: {
    id: 'enemy_anti_heal_aura',
    label: 'Аура анти-хила',
    semanticEmojiId: 'skull-green',
    classFlavor: 'warlock',
    effectKind: 'conditional',
    levelTrigger: 'on_turn_start',
    ops: [{ kind: 'heal_mult', base: -0.25, scaleMode: 'percent' }],
    synergies: ['monster_plague_cloud'],
    descriptionRu: 'Соседние герои получают на 25% меньше исцеления.',
  },
  enemy_anti_mana: {
    id: 'enemy_anti_mana',
    label: 'Анти-магия',
    semanticEmojiId: 'orb-purple',
    classFlavor: 'warlock',
    effectKind: 'proc',
    levelTrigger: 'on_card_attack',
    procChance: 1,
    ops: [{ kind: 'mana_cost_mult', base: 0.25, scaleMode: 'percent' }],
    synergies: ['monster_mana_siphon'],
    descriptionRu: 'При попадании умением снижает эффективность магии цели.',
  },
  enemy_rage_trait: {
    id: 'enemy_rage_trait',
    label: 'Яростный трейт',
    semanticEmojiId: 'axe-red',
    classFlavor: 'berserker',
    effectKind: 'conditional',
    levelTrigger: 'on_strike',
    statId: 'attack',
    baseFlat: 2,
    ops: [{ kind: 'damage_mult', base: 0.25, scaleMode: 'percent' }],
    synergies: ['frenzy'],
    descriptionRu: '+2 к атаке и +25% к урону при HP ниже 50%.',
  },
  enemy_holy_ward: {
    id: 'enemy_holy_ward',
    label: 'Святой страж',
    semanticEmojiId: 'shield-gold',
    classFlavor: 'paladin',
    effectKind: 'conditional',
    levelTrigger: 'on_card_attack',
    ops: [{ kind: 'damage_mult', base: 0.2, scaleMode: 'percent' }],
    synergies: ['holy_strike'],
    descriptionRu: '+20% к святому урону умений.',
  },
  enemy_thorns: {
    id: 'enemy_thorns',
    label: 'Шипы',
    semanticEmojiId: 'shield-gray',
    classFlavor: 'warrior',
    effectKind: 'conditional',
    levelTrigger: 'on_damaged',
    ops: [{ kind: 'reflect_on_hit', base: 20, scaleMode: 'percent' }],
    synergies: ['shield_bash'],
    descriptionRu: 'Отражает 20% полученного ближнего урона атакующему.',
  },
  enemy_dark_affinity: {
    id: 'enemy_dark_affinity',
    label: 'Тёмная аффинность',
    semanticEmojiId: 'orb-purple',
    classFlavor: 'warlock',
    effectKind: 'conditional',
    levelTrigger: 'on_card_attack',
    ops: [{ kind: 'damage_mult', base: 0.15, scaleMode: 'percent' }],
    synergies: ['shadow_bolt'],
    descriptionRu: '+15% к тёмному урону умений.',
  },
  boss_ignore_armor: {
    id: 'boss_ignore_armor',
    label: 'Игнор брони',
    semanticEmojiId: 'shield-gray',
    classFlavor: 'warrior',
    effectKind: 'conditional',
    levelTrigger: 'on_strike',
    ops: [{ kind: 'damage_mult', base: 0.5, scaleMode: 'percent' }],
    synergies: ['boss_ground_slam'],
    descriptionRu: 'Атаки игнорируют 50% защиты цели.',
  },
  boss_ranged_ward: {
    id: 'boss_ranged_ward',
    label: 'Дальний страж',
    semanticEmojiId: 'shield-gold',
    classFlavor: 'rogue',
    effectKind: 'conditional',
    levelTrigger: 'on_damaged',
    ops: [{ kind: 'reflect_on_hit', base: 50, scaleMode: 'percent' }],
    synergies: ['boss_blink_adjacent'],
    descriptionRu: 'Урон от дальних атак снижен на 50%.',
  },
  boss_no_flank: {
    id: 'boss_no_flank',
    label: 'Без фланга',
    semanticEmojiId: 'shield-gray',
    classFlavor: 'warrior',
    effectKind: 'conditional',
    levelTrigger: 'on_turn_start',
    ops: [],
    synergies: ['boss_ward_pulse'],
    descriptionRu: 'Нельзя атаковать с фланга или со спины.',
  },
  boss_reflect_rage: {
    id: 'boss_reflect_rage',
    label: 'Зеркальная ярость',
    semanticEmojiId: 'blood-red',
    classFlavor: 'berserker',
    effectKind: 'conditional',
    levelTrigger: 'on_damaged',
    ops: [{ kind: 'reflect_on_hit', base: 30, scaleMode: 'percent' }],
    synergies: ['boss_mirror_rage'],
    descriptionRu: 'Отражает 30% полученного ближнего урона атакующему.',
  },
}

export const ENEMY_PASSIVE_TEMPLATE_IDS: readonly string[] = Object.keys(ENEMY_PASSIVE_TEMPLATES)

export function getEnemyPassiveTemplate(id: string): PassiveTemplate | undefined {
  return ENEMY_PASSIVE_TEMPLATES[id]
}
