import type { ClassId, StatId } from '../config/baseStats'
import type { EquipmentSlot } from '../types'
import type { SpecModId } from './modTemplates'

export type ItemTemplate = {
  /** Совпадает с ключом в каталоге и с `ItemInstance.templateId`. */
  id: string
  slot: EquipmentSlot
  shopPrice: number
  hpPctPerLevel: number
  /** @deprecated migrate to statPctPerLevel.attack */
  damagePctPerLevel: number
  statPctPerLevel?: Partial<Record<StatId, number>>
  label: string
  tags: readonly string[]
  semanticEmojiId: string
  recommendedClassId?: ClassId
  modAffinity?: readonly SpecModId[]
  /** @deprecated use semanticEmojiId */
  emoji?: string
}

export const ITEM_TEMPLATES: Readonly<Record<string, ItemTemplate>> = {
  wooden_sword: {
    id: 'wooden_sword',
    slot: 'weapon',
    shopPrice: 10,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Деревянный меч',
    tags: ['weapon', 'attack', 'melee'],
    semanticEmojiId: 'sword-red',
    emoji: '🗡️',
  },
  leather_armor: {
    id: 'leather_armor',
    slot: 'armor',
    shopPrice: 15,
    hpPctPerLevel: 2,
    damagePctPerLevel: 0,
    label: 'Кожаная броня',
    tags: ['armor', 'defense'],
    semanticEmojiId: 'gi-teal',
    emoji: '🥋',
  },
  copper_ring: {
    id: 'copper_ring',
    slot: 'accessory',
    shopPrice: 20,
    hpPctPerLevel: 1,
    damagePctPerLevel: 1,
    label: 'Медное кольцо',
    tags: ['accessory'],
    semanticEmojiId: 'ring-gold',
    emoji: '💍',
  },
  warrior_blade: {
    id: 'warrior_blade',
    slot: 'weapon',
    shopPrice: 35,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Клинок воина',
    tags: ['weapon', 'attack', 'melee'],
    semanticEmojiId: 'sword-red',
    recommendedClassId: 'warrior',
    modAffinity: ['mod-weapon-damage', 'mod-crit-chance', 'mod-double-strike'],
  },
  warrior_plate: {
    id: 'warrior_plate',
    slot: 'armor',
    shopPrice: 40,
    hpPctPerLevel: 3,
    damagePctPerLevel: 0,
    label: 'Латы',
    tags: ['armor', 'defense'],
    semanticEmojiId: 'shield-gray',
    recommendedClassId: 'warrior',
    modAffinity: ['mod-armor-bonus', 'mod-hp-bonus-armor', 'mod-thorns'],
  },
  warrior_signet: {
    id: 'warrior_signet',
    slot: 'accessory',
    shopPrice: 30,
    hpPctPerLevel: 2,
    damagePctPerLevel: 1,
    label: 'Печать силы',
    tags: ['accessory'],
    semanticEmojiId: 'ring-gold',
    recommendedClassId: 'warrior',
    modAffinity: ['mod-initiative', 'mod-hp-bonus-accessory'],
  },
  mage_staff: {
    id: 'mage_staff',
    slot: 'weapon',
    shopPrice: 38,
    hpPctPerLevel: 0,
    damagePctPerLevel: 2,
    label: 'Посох мага',
    tags: ['weapon', 'attack', 'ranged'],
    semanticEmojiId: 'orb-purple',
    recommendedClassId: 'mage',
    modAffinity: ['mod-damage-up', 'mod-aoe-size', 'mod-cooldown-down'],
  },
  mage_robe: {
    id: 'mage_robe',
    slot: 'armor',
    shopPrice: 35,
    hpPctPerLevel: 1,
    damagePctPerLevel: 1,
    label: 'Мантия мага',
    tags: ['armor'],
    semanticEmojiId: 'robe-purple',
    recommendedClassId: 'mage',
    modAffinity: ['mod-mana-save', 'mod-cooldown-down'],
  },
  mage_crystal: {
    id: 'mage_crystal',
    slot: 'accessory',
    shopPrice: 28,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Кристалл маны',
    tags: ['accessory'],
    semanticEmojiId: 'orb-blue',
    recommendedClassId: 'mage',
    modAffinity: ['mod-initiative', 'mod-cooldown-down'],
  },
  ranger_bow: {
    id: 'ranger_bow',
    slot: 'weapon',
    shopPrice: 35,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Лук следопыта',
    tags: ['weapon', 'attack', 'ranged'],
    semanticEmojiId: 'bow-teal',
    recommendedClassId: 'ranger',
    modAffinity: ['mod-range-up', 'mod-crit-chance', 'mod-weapon-damage'],
  },
  ranger_leathers: {
    id: 'ranger_leathers',
    slot: 'armor',
    shopPrice: 32,
    hpPctPerLevel: 2,
    damagePctPerLevel: 0,
    label: 'Доспех следопыта',
    tags: ['armor', 'defense'],
    semanticEmojiId: 'gi-teal',
    recommendedClassId: 'ranger',
    modAffinity: ['mod-initiative', 'mod-heal-on-hit-taken'],
  },
  ranger_charm: {
    id: 'ranger_charm',
    slot: 'accessory',
    shopPrice: 28,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Амулет меткости',
    tags: ['accessory'],
    semanticEmojiId: 'target-teal',
    recommendedClassId: 'ranger',
    modAffinity: ['mod-crit-chance', 'mod-initiative'],
  },
  healer_staff: {
    id: 'healer_staff',
    slot: 'weapon',
    shopPrice: 30,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Посох лекаря',
    tags: ['weapon', 'heal'],
    semanticEmojiId: 'heal-red',
    recommendedClassId: 'healer',
    modAffinity: ['mod-heal-up', 'mod-self-heal-on-use'],
  },
  healer_mantle: {
    id: 'healer_mantle',
    slot: 'armor',
    shopPrice: 38,
    hpPctPerLevel: 3,
    damagePctPerLevel: 0,
    label: 'Мантия целителя',
    tags: ['armor', 'heal'],
    semanticEmojiId: 'heal-blue',
    recommendedClassId: 'healer',
    modAffinity: ['mod-heal-on-hit-taken', 'mod-ally-heal-splash'],
  },
  healer_ring: {
    id: 'healer_ring',
    slot: 'accessory',
    shopPrice: 25,
    hpPctPerLevel: 2,
    damagePctPerLevel: 0,
    label: 'Кольцо света',
    tags: ['accessory', 'heal'],
    semanticEmojiId: 'ring-gold',
    recommendedClassId: 'healer',
    modAffinity: ['mod-accessory-regen', 'mod-heal-up'],
  },
  rogue_dagger: {
    id: 'rogue_dagger',
    slot: 'weapon',
    shopPrice: 32,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Кинжалы',
    tags: ['weapon', 'attack', 'melee'],
    semanticEmojiId: 'dagger-purple',
    recommendedClassId: 'rogue',
    modAffinity: ['mod-crit-chance', 'mod-double-strike', 'mod-lifesteal'],
  },
  rogue_cloak: {
    id: 'rogue_cloak',
    slot: 'armor',
    shopPrice: 30,
    hpPctPerLevel: 1,
    damagePctPerLevel: 0,
    label: 'Плащ теней',
    tags: ['armor', 'defense'],
    semanticEmojiId: 'mask-gray',
    recommendedClassId: 'rogue',
    modAffinity: ['mod-initiative', 'mod-heal-on-hit-taken'],
  },
  rogue_ring: {
    id: 'rogue_ring',
    slot: 'accessory',
    shopPrice: 28,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Кольцо удара',
    tags: ['accessory'],
    semanticEmojiId: 'target-purple',
    recommendedClassId: 'rogue',
    modAffinity: ['mod-crit-chance', 'mod-triple-strike'],
  },
  paladin_mace: {
    id: 'paladin_mace',
    slot: 'weapon',
    shopPrice: 35,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Булава паладина',
    tags: ['weapon', 'attack', 'melee'],
    semanticEmojiId: 'sword-gold',
    recommendedClassId: 'paladin',
    modAffinity: ['mod-weapon-damage', 'mod-self-heal-on-attack'],
  },
  paladin_aegis: {
    id: 'paladin_aegis',
    slot: 'armor',
    shopPrice: 42,
    hpPctPerLevel: 3,
    damagePctPerLevel: 0,
    label: 'Эгида',
    tags: ['armor', 'defense'],
    semanticEmojiId: 'shield-gold',
    recommendedClassId: 'paladin',
    modAffinity: ['mod-armor-bonus', 'mod-thorns', 'mod-hp-bonus-armor'],
  },
  paladin_reliquary: {
    id: 'paladin_reliquary',
    slot: 'accessory',
    shopPrice: 32,
    hpPctPerLevel: 2,
    damagePctPerLevel: 0,
    label: 'Реликварий',
    tags: ['accessory', 'heal'],
    semanticEmojiId: 'spark-gold',
    recommendedClassId: 'paladin',
    modAffinity: ['mod-heal-up', 'mod-hp-bonus-accessory'],
  },
  warlock_staff: {
    id: 'warlock_staff',
    slot: 'weapon',
    shopPrice: 40,
    hpPctPerLevel: 0,
    damagePctPerLevel: 2,
    label: 'Посох колдуна',
    tags: ['weapon', 'attack', 'ranged'],
    semanticEmojiId: 'orb-purple',
    recommendedClassId: 'warlock',
    modAffinity: ['mod-damage-up', 'mod-lifesteal', 'mod-crit-chance'],
  },
  warlock_shroud: {
    id: 'warlock_shroud',
    slot: 'armor',
    shopPrice: 35,
    hpPctPerLevel: 2,
    damagePctPerLevel: 0,
    label: 'Мрачная мантия',
    tags: ['armor', 'defense'],
    semanticEmojiId: 'moon-purple',
    recommendedClassId: 'warlock',
    modAffinity: ['mod-heal-on-hit-taken', 'mod-thorns'],
  },
  warlock_soul_gem: {
    id: 'warlock_soul_gem',
    slot: 'accessory',
    shopPrice: 30,
    hpPctPerLevel: 0,
    damagePctPerLevel: 1,
    label: 'Камень душ',
    tags: ['accessory'],
    semanticEmojiId: 'skull-purple',
    recommendedClassId: 'warlock',
    modAffinity: ['mod-lifesteal', 'mod-self-heal-on-attack'],
  },
  berserker_axe: {
    id: 'berserker_axe',
    slot: 'weapon',
    shopPrice: 40,
    hpPctPerLevel: 0,
    damagePctPerLevel: 2,
    label: 'Топор берсерка',
    tags: ['weapon', 'attack', 'melee'],
    semanticEmojiId: 'axe-red',
    recommendedClassId: 'berserker',
    modAffinity: ['mod-weapon-damage', 'mod-double-strike', 'mod-triple-strike'],
  },
  berserker_harness: {
    id: 'berserker_harness',
    slot: 'armor',
    shopPrice: 38,
    hpPctPerLevel: 2,
    damagePctPerLevel: 0,
    label: 'Нагрудник ярости',
    tags: ['armor', 'defense'],
    semanticEmojiId: 'blood-red',
    recommendedClassId: 'berserker',
    modAffinity: ['mod-heal-on-hit-taken', 'mod-thorns'],
  },
  berserker_amulet: {
    id: 'berserker_amulet',
    slot: 'accessory',
    shopPrice: 32,
    hpPctPerLevel: 1,
    damagePctPerLevel: 1,
    label: 'Амулет крови',
    tags: ['accessory'],
    semanticEmojiId: 'blood-red',
    recommendedClassId: 'berserker',
    modAffinity: ['mod-lifesteal', 'mod-self-heal-on-attack'],
  },
}

export function getItemTemplate(templateId: string): ItemTemplate | undefined {
  return ITEM_TEMPLATES[templateId]
}

export const SHOP_TEMPLATE_IDS: readonly string[] = Object.keys(ITEM_TEMPLATES)
