import type { CardAttackTemplate } from './cardTemplates'

export const MONSTER_SKILL_TEMPLATES: Readonly<Record<string, CardAttackTemplate>> = {
  monster_bite: {
    label: 'Укус',
    kind: 'melee',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 2,
    scaleToken: '35%%',
    cooldownTurns: 4,
    tags: ['skill', 'attack', 'melee', 'poison', 'dot'],
    semanticEmojiId: 'drop-green',
  },
  monster_roar: {
    label: 'Рык',
    kind: 'debuff',
    maxRange: 1,
    aoeSize: 3,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '20%%',
    cooldownTurns: 6,
    tags: ['skill', 'debuff', 'aoe'],
    semanticEmojiId: 'horn-gold',
  },
  monster_bone_throw: {
    label: 'Костяной бросок',
    kind: 'ranged',
    maxRange: 4,
    statSource: 'attack',
    skillFlat: 3,
    scaleToken: '45%%',
    cooldownTurns: 4,
    tags: ['skill', 'attack', 'ranged'],
    semanticEmojiId: 'skull-green',
  },
  monster_mana_siphon: {
    label: 'Высасывание маны',
    kind: 'debuff',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 2,
    scaleToken: '35%%',
    cooldownTurns: 6,
    tags: ['skill', 'debuff', 'ranged', 'magic'],
    semanticEmojiId: 'orb-purple',
  },
  monster_armor_break: {
    label: 'Разлом брони',
    kind: 'debuff',
    maxRange: 1,
    statSource: 'attack',
    skillFlat: 2,
    scaleToken: '30%%',
    cooldownTurns: 6,
    tags: ['skill', 'debuff', 'melee', 'attack'],
    semanticEmojiId: 'shield-gray',
  },
  monster_plague_cloud: {
    label: 'Чумное облако',
    kind: 'aoe',
    maxRange: 3,
    aoeSize: 3,
    statSource: 'magicPower',
    skillFlat: 2,
    scaleToken: '40%%',
    cooldownTurns: 8,
    tags: ['skill', 'attack', 'aoe', 'dot', 'poison'],
    semanticEmojiId: 'skull-green',
  },
  boss_ground_slam: {
    label: 'Удар по земле',
    kind: 'aoe',
    maxRange: 1,
    aoeSize: 5,
    statSource: 'attack',
    skillFlat: 5,
    scaleToken: '55%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'melee', 'aoe'],
    semanticEmojiId: 'axe-red',
  },
  boss_spell_eater: {
    label: 'Пожирание заклинания',
    kind: 'utility',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '0%%',
    cooldownTurns: 4,
    tags: ['skill', 'debuff', 'magic', 'utility'],
    semanticEmojiId: 'orb-purple',
  },
  boss_blink_adjacent: {
    label: 'Мгновенный рывок',
    kind: 'utility',
    maxRange: 8,
    statSource: 'speed',
    skillFlat: 0,
    scaleToken: '0%%',
    cooldownTurns: 6,
    tags: ['skill', 'mobility', 'utility'],
    semanticEmojiId: 'smoke-gray',
  },
  boss_soul_mark: {
    label: 'Метка души',
    kind: 'debuff',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 1,
    scaleToken: '25%%',
    cooldownTurns: 8,
    tags: ['skill', 'debuff', 'dark'],
    semanticEmojiId: 'skull-green',
  },
  boss_grave_silence: {
    label: 'Могильная тишина',
    kind: 'debuff',
    maxRange: 3,
    aoeSize: 3,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '20%%',
    cooldownTurns: 10,
    tags: ['skill', 'debuff', 'aoe', 'dark'],
    semanticEmojiId: 'skull-green',
  },
  boss_ward_pulse: {
    label: 'Импульс стража',
    kind: 'aoe',
    maxRange: 2,
    aoeSize: 5,
    statSource: 'magicPower',
    skillFlat: 4,
    scaleToken: '50%%',
    cooldownTurns: 6,
    tags: ['skill', 'attack', 'magic', 'aoe'],
    semanticEmojiId: 'spark-purple',
  },
  boss_decay_aura: {
    label: 'Аура упадка',
    kind: 'debuff',
    maxRange: 2,
    aoeSize: 5,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '25%%',
    cooldownTurns: 8,
    tags: ['skill', 'debuff', 'aoe', 'holy'],
    semanticEmojiId: 'spark-gold',
  },
  boss_holy_judgment: {
    label: 'Святой суд',
    kind: 'aoe',
    maxRange: 4,
    aoeSize: 3,
    statSource: 'magicPower',
    skillFlat: 5,
    scaleToken: '55%%',
    cooldownTurns: 8,
    tags: ['skill', 'attack', 'holy', 'aoe'],
    semanticEmojiId: 'spark-gold',
  },
  boss_silence_dark: {
    label: 'Тишина тьмы',
    kind: 'debuff',
    maxRange: 4,
    statSource: 'magicPower',
    skillFlat: 0,
    scaleToken: '20%%',
    cooldownTurns: 8,
    tags: ['skill', 'debuff', 'dark'],
    semanticEmojiId: 'orb-purple',
  },
  boss_mirror_rage: {
    label: 'Зеркальная ярость',
    kind: 'buff',
    maxRange: 4,
    statSource: 'attack',
    skillFlat: 0,
    scaleToken: '30%%',
    cooldownTurns: 10,
    tags: ['skill', 'buff', 'utility'],
    semanticEmojiId: 'blood-red',
  },
}

export const MONSTER_SKILL_TEMPLATE_IDS: readonly string[] = Object.keys(MONSTER_SKILL_TEMPLATES)

export function getMonsterSkillTemplate(templateId: string): CardAttackTemplate | undefined {
  return MONSTER_SKILL_TEMPLATES[templateId]
}
